backend:
  name: git-gateway
  branch: main
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'data'
    label: 'Δεδομένα'
    files:
      - label: 'Επικοινωνία'
        name: 'contact'
        file: 'content/data/contact.md'
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Content"
            name: "body"
            widget: "markdown"
            buttons:
              - bold
              - italic
              - link
              - heading-two
              - heading-three
              - heading-four
              - bulleted-list
      - label: 'Μενού'
        name: 'school-menu'
        file: 'content/data/menu.md'
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
          - label: 'pages'
            name: 'pages'
            widget: 'list'
            fields:
              - label: 'Page'
                name: 'page'
                widget: 'relation'
                collection: 'pages'
                search_fields: ['title']
                value_field: 'title'
                display_fields: ['title']
  - name: 'pages'
    label: 'Σελίδες'
    folder: 'content/pages'
    create: true
    slug: '{{url_slug}}'
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "URL"
        name: "url_slug"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        editor_components:
          - image
  - name: 'posts'
    label: 'Νέα'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}'
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Content"
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        editor_components:
          - image
  - name: 'draseis'
    label: 'Δράσεις'
    folder: 'content/draseis'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}'
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Introduction"
        name: "intro"
        widget: "text"
      - label: "Content"
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        editor_components:
          - image
  - name: 'anakoinoseis'
    label: 'Ανακοινώσεις'
    folder: 'content/anakoinoseis'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}'
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Content"
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - bulleted-list
          - numbered-list
        editor_components:
          - image
  - name: 'fundings'
    label: 'Χρηματοδοτήσεις'
    folder: 'content/fundings'
    create: true
    slug: '{{url_slug}}'
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "URL"
        name: "url_slug"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - link
          - heading-two
          - heading-three
          - heading-four
          - bulleted-list
          - numbered-list
        editor_components:
          - image
